Repository Pryaxis/TSAPI, pull requests merged in 2021-11, with the labels that each got.

#197 Updating modifications target assembly to 1.4.3.0
  .editorconfig
  TShock.Modifications.Bootstrapper/TShock.Modifications.Bootstrapper.csproj
  TShock.Modifications.Bootstrapper/packages.config
  TShock.Modifications.ClientUUID/ClientUUID.cs
  TShock.Modifications.ConnectionLoop/ConnectionLoop.cs
  TShock.Modifications.ConnectionLoop/TShock.Modifications.ConnectionLoop.csproj
  TShock.Modifications.ConnectionLoop/packages.config
  TShock.Modifications.Explosives/Explosives.cs
  TShock.Modifications.Platform/PlatformModification.cs
  TShock.Modifications.Platform/TShock.Modifications.Platform.csproj
  TShock.Modifications.Platform/packages.config
  TShock.Modifications.SSC/SSC.cs
  TShock.Modifications.SSC/TShock.Modifications.SSC.csproj
  TShock.Modifications.SSC/packages.config
  TerrariaServerAPI/Properties/AssemblyInfo.cs
Labels: size/M

#198 1.4.3.0 with OTAPI3
  .gitignore
  TSAPI.sln
  TShock.4.OTAPI.sln
  TShock.Modifications.Bootstrapper/App.config
  TShock.Modifications.Bootstrapper/Program.cs
  TShock.Modifications.Bootstrapper/Properties/AssemblyInfo.cs
  TShock.Modifications.Bootstrapper/TShock.Modifications.Bootstrapper.csproj
  TShock.Modifications.Bootstrapper/packages.config
  TShock.Modifications.ClientUUID/ClientUUID.cs
  TShock.Modifications.ClientUUID/Properties/AssemblyInfo.cs
  TShock.Modifications.ClientUUID/TShock.Modifications.ClientUUID.csproj
  TShock.Modifications.ClientUUID/packages.config
  TShock.Modifications.ConnectionLoop/ConnectionLoop.cs
  TShock.Modifications.ConnectionLoop/Properties/AssemblyInfo.cs
  TShock.Modifications.ConnectionLoop/TShock.Modifications.ConnectionLoop.csproj
  TShock.Modifications.ConnectionLoop/packages.config
  TShock.Modifications.Explosives/Explosives.cs
  TShock.Modifications.Explosives/Properties/AssemblyInfo.cs
  TShock.Modifications.Explosives/TShock.Modifications.Explosives.csproj
  TShock.Modifications.Explosives/packages.config
  TShock.Modifications.Platform/Callbacks/PlatformConstructorCallback.cs
  TShock.Modifications.Platform/PlatformModification.cs
  TShock.Modifications.Platform/Properties/AssemblyInfo.cs
  TShock.Modifications.Platform/TShock.Modifications.Platform.csproj
  TShock.Modifications.Platform/packages.config
  TShock.Modifications.SSC/Properties/AssemblyInfo.cs
  TShock.Modifications.SSC/SSC.cs
  TShock.Modifications.SSC/TShock.Modifications.SSC.csproj
  TShock.Modifications.SSC/packages.config
  TerrariaServerAPI/Steamworks.NET.dll
  TerrariaServerAPI/TerrariaApi.Server/HookManager.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/GameHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ItemHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NetHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NpcHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ProjectileHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ServerHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/WiringHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/WorldHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/TileProvider.cs
  TerrariaServerAPI/TerrariaServerAPI.csproj
  TerrariaServerAPI/TerrariaServerReferences/Microsoft.Xna.Framework.Game.dll
  TerrariaServerAPI/TerrariaServerReferences/Microsoft.Xna.Framework.Graphics.dll
  TerrariaServerAPI/TerrariaServerReferences/Microsoft.Xna.Framework.Xact.dll
  TerrariaServerAPI/TerrariaServerReferences/Terraria.Libraries.JSON.NET.Net40.Newtonsoft.Json.dll
  TerrariaServerAPI/TerrariaServerReferences/Terraria.Libraries.Steamworks.NET.Steamworks.NET.dll
  TerrariaServerAPI/app.config
  TerrariaServerAPI/packages.config
  build_instructions.txt
Labels: size/XXL

#199 Updating modifications target assembly to 1.4.3.1
  TShock.Modifications.Bootstrapper/TShock.Modifications.Bootstrapper.csproj
  TShock.Modifications.Bootstrapper/packages.config
  TShock.Modifications.ClientUUID/ClientUUID.cs
  TShock.Modifications.ConnectionLoop/ConnectionLoop.cs
  TShock.Modifications.ConnectionLoop/TShock.Modifications.ConnectionLoop.csproj
  TShock.Modifications.ConnectionLoop/packages.config
  TShock.Modifications.Explosives/Explosives.cs
  TShock.Modifications.Platform/PlatformModification.cs
  TShock.Modifications.Platform/TShock.Modifications.Platform.csproj
  TShock.Modifications.Platform/packages.config
  TShock.Modifications.SSC/SSC.cs
  TShock.Modifications.SSC/TShock.Modifications.SSC.csproj
  TShock.Modifications.SSC/packages.config
  TerrariaServerAPI/Properties/AssemblyInfo.cs
Labels: size/M

#200 Update OTAPI to 3.0.22-alpha
  TerrariaServerAPI/TerrariaServerAPI.csproj
Labels: size/XS

#201 Remove old solution file
  TerrariaServerAPI/TerrariaServer.sln
Labels: size/M

#202 Update modifications target assembly to 1.4.3.2, target to OTAPI 2.0.…
  TShock.Modifications.Bootstrapper/TShock.Modifications.Bootstrapper.csproj
  TShock.Modifications.Bootstrapper/packages.config
  TShock.Modifications.ClientUUID/ClientUUID.cs
  TShock.Modifications.ConnectionLoop/ConnectionLoop.cs
  TShock.Modifications.ConnectionLoop/TShock.Modifications.ConnectionLoop.csproj
  TShock.Modifications.ConnectionLoop/packages.config
  TShock.Modifications.Explosives/Explosives.cs
  TShock.Modifications.Platform/PlatformModification.cs
  TShock.Modifications.Platform/TShock.Modifications.Platform.csproj
  TShock.Modifications.Platform/packages.config
  TShock.Modifications.SSC/SSC.cs
  TShock.Modifications.SSC/TShock.Modifications.SSC.csproj
  TShock.Modifications.SSC/packages.config
  TerrariaServerAPI/Properties/AssemblyInfo.cs
Labels: size/M
