Repository Pryaxis/TSAPI, pull requests merged in 2022-10, with the labels that each got.

#213 Add missing `PacketTypes` definitions from `1.4.4`
  TerrariaServerAPI/TerrariaApi.Server/PacketTypes.cs
Labels: size/XS

#220 Change base path for plugins to use AppContext.BaseDirectory
  TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
Labels: size/XS

#225 Fix tombstones and other "disable projectile" settings
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ProjectileHooks.cs
Labels: size/XS

#223 Fix heaptile field offsets
  TerrariaServerAPI/TerrariaApi.Server/HeapTile.cs
  TerrariaServerAPI/TerrariaApi.Server/HookManager.cs
Labels: size/M

#228 Test failed plugins for incompatible architectures
  TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
Labels: size/M

#227 Introduce a new tile provider: Constileation
  .github/workflows/build.yml
  .github/workflows/nuget.yml
  .gitignore
  TerrariaServerAPI.Tests/BaseTest.cs
  TerrariaServerAPI.Tests/ServerInitTests.cs
  TerrariaServerAPI.Tests/TerrariaServerAPI.Tests.csproj
  TerrariaServerAPI.Tests/TileBenchmarks.cs
  TerrariaServerAPI/Properties/AssemblyInfo.cs
  TerrariaServerAPI/TerrariaApi.Server/ConstileationProvider.cs
  TerrariaServerAPI/TerrariaApi.Server/HookManager.cs
Labels: size/L

#230 Add -additionalplugins flag
  TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
Labels: size/S

#231 Constileation updates and add in benchmarks to show comparisons between current providers
  .github/workflows/build.yml
  .github/workflows/nuget.yml
  TerrariaServerAPI.Tests/Benchmarks/Benchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileActiveBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileAssignsFromSelfBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileAssignsFromTileBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileClearBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileClearWorldBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileGetsBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileTypeBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/TileUseBenchmarks.cs
  TerrariaServerAPI.Tests/Benchmarks/_TileBenchmarks.cs
  TerrariaServerAPI.Tests/TerrariaServerAPI.Tests.csproj
  TerrariaServerAPI.Tests/TileBenchmarks.cs
  TerrariaServerAPI.Tests/TileGenerateTests.cs
  TerrariaServerAPI/TerrariaApi.Server/ConstileationProvider.cs
Labels: size/XL

#234 -nolog startup flag
  TerrariaServerAPI/TerrariaApi.Server/LogWriterManager.cs
  TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
Labels: size/M
