Repository Pryaxis/TSAPI, pull requests merged in 2025-01, with the labels that each got.

#247 Respect OTAPI hook result
  TerrariaServerAPI/TerrariaApi.Server/Hooking/GameHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ItemHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NetHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NpcHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ServerHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/WiringHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/WorldHooks.cs
Labels: size/M

#251 Also load symbols in AssemblyResolve
  TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
Labels: size/XS

#250 Show IL offsets
  TerrariaServerAPI/TerrariaApi.Server/ServerApi.cs
Labels: size/XS

#253 fix: forceupdate
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NetHooks.cs
Labels: size/S

#254 Upgrade to .NET 9 and OTAPI Static Hooks for ARM64
  .github/workflows/build.yml
  .github/workflows/nuget.yml
  TerrariaServerAPI.Tests/BaseTest.cs
  TerrariaServerAPI.Tests/ServerInitTests.cs
  TerrariaServerAPI.Tests/TerrariaServerAPI.Tests.csproj
  TerrariaServerAPI/TerrariaApi.Server/HookManager.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/GameHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ItemHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NetHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/NpcHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ProjectileHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/ServerHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/WiringHooks.cs
  TerrariaServerAPI/TerrariaApi.Server/Hooking/WorldHooks.cs
  TerrariaServerAPI/TerrariaServerAPI.csproj
Labels: size/XXL
